language: c

compiler: gcc

env:
    global:
        - ZEPHYR_SDK_INSTALL_DIR=/opt/sdk/zephyr-sdk-0.10.3
        - ZEPHYR_TOOLCHAIN_VARIANT=zephyr
        - MATRIX_BUILDS="30"
    matrix:
        - MATRIX_BUILD="1"
        - MATRIX_BUILD="2"
        - MATRIX_BUILD="3"
        - MATRIX_BUILD="4"
        - MATRIX_BUILD="5"
        - MATRIX_BUILD="6"
        - MATRIX_BUILD="7"
        - MATRIX_BUILD="8"
        - MATRIX_BUILD="9"
        - MATRIX_BUILD="10"
        - MATRIX_BUILD="11"
        - MATRIX_BUILD="12"
        - MATRIX_BUILD="13"
        - MATRIX_BUILD="14"
        - MATRIX_BUILD="15"
        - MATRIX_BUILD="16"
        - MATRIX_BUILD="17"
        - MATRIX_BUILD="18"
        - MATRIX_BUILD="19"
        - MATRIX_BUILD="20"
        - MATRIX_BUILD="21"
        - MATRIX_BUILD="22"
        - MATRIX_BUILD="23"
        - MATRIX_BUILD="24"
        - MATRIX_BUILD="25"
        - MATRIX_BUILD="26"
        - MATRIX_BUILD="27"
        - MATRIX_BUILD="28"
        - MATRIX_BUILD="29"
        - MATRIX_BUILD="30"

build:
    cache: false
    cache_dir_list:
        - ${SHIPPABLE_BUILD_DIR}/ccache
    pre_ci_boot:
        image_name: zephyrprojectrtos/ci
        image_tag: v0.11.0
        pull: true
        options: "-e HOME=/home/buildslave --privileged=true --tty --net=bridge --user buildslave"

    ci:
      - export CCACHE_DIR=${SHIPPABLE_BUILD_DIR}/ccache/.ccache
      - >
        if [ "$IS_PULL_REQUEST" = "true" ]; then
          ./scripts/ci/run_ci.sh -c -b ${PULL_REQUEST_BASE_BRANCH} -r origin -m ${MATRIX_BUILD} -M ${MATRIX_BUILDS} -p ${PULL_REQUEST};
        else
          ./scripts/ci/run_ci.sh -c -b ${BRANCH} -r origin -m ${MATRIX_BUILD} -M ${MATRIX_BUILDS};
        fi;
      - ccache -s
    on_failure:
      - >
        if [ "$IS_PULL_REQUEST" = "true" ]; then
          ./scripts/ci/run_ci.sh -f -b ${PULL_REQUEST_BASE_BRANCH} -r origin -m ${MATRIX_BUILD} -M ${MATRIX_BUILDS} -p ${PULL_REQUEST};
        else
          ./scripts/ci/run_ci.sh -f -b ${BRANCH} -r origin -m ${MATRIX_BUILD} -M ${MATRIX_BUILDS};
        fi;
    on_success:
      - >
        if [ "$IS_PULL_REQUEST" = "true" ]; then
          ./scripts/ci/run_ci.sh -s -b ${PULL_REQUEST_BASE_BRANCH} -r origin -m ${MATRIX_BUILD} -M ${MATRIX_BUILDS} -p ${PULL_REQUEST};
        else
          ./scripts/ci/run_ci.sh -s -b ${BRANCH} -r origin -m ${MATRIX_BUILD} -M ${MATRIX_BUILDS};
        fi;
branches:
  only:
    - master
    - v*-branch
    - topic-*
integrations:
  notifications:
    - integrationName: slack_integration
      type: slack
      recipients:
        - "#ci"
      branches:
        only:
          - master
      on_success: never
      on_failure: never
    - integrationName: email
      type: email
      recipients:
        - builds@zephyrproject.org
      branches:
        only:
          - master
      on_success: never
      on_failure: always
      on_pull_request: never
